---
- name: Run the command or configuration on devices
  hosts: all
  roles:
    - Juniper.junos
  gather_facts: no
  connection: local

  tasks:
    - name: Send a command to Juniper device
      juniper_junos_command:
        provider:
          host: "{{ ansible_host }}"
          user: "jnpr"
        commands:
          - set services rpm twamp server authentication-mode none
      register: junos_result

    - name: Print response
      debug:
        var: junos_result.stdout_lines
